### ISSUE TITLE
счёт во время игры

### ISSUE THREAD

**Issue by iluha23** [Zeneriode/Snake-game#27]
во время игры будет показываться счёт в углах экрана в зависимости от положения змеи

**Comment by Zener085** [comment]
1) Анализировать вектор приоритетов (что был создан на уроке) и найти индекс самого малого числа (`draw_numbers.py`).
2) Сделать 3 метода, которые будут рисовать `1`, `2` или `3` цифры в разных углах игрового окна (предыдущие методы рисуют цифры только в центре) (`draw_numbers.py`)
3) Создать функцию, которая анализирует местонахождение объектов в игре и составляет вектор приоритетов четвертей, а также вызывает метод прорисовки счета в игре (`main.py`).
4) Протестировать работу всего алгоритма в игре, подкорректировать все проблемы и вопросы
